### ISSUE TITLE
Rename `is_mentor` to `is_faculty`

### ISSUE THREAD

**Issue by razzius** [razzius/weave#150]
We already have is_mentor, but if we want students to be able to mentor, we need another way to keep track of who is a student. Solution: `is_faculty` field on `VerificationEmail.`

- faculty should not see students when they browse profiles
- admin should be able to view and edit this field
- New button on homepage for students `browse student mentors`
  - wording -> browse faculty profiles

**Comment by razzius** [comment]
New button for students "create peer mentor profile" on home page

**Comment by Chronowork1** [comment]
Finished!

**Comment by razzius** [comment]
Great @Chronowork1! Could you make a pull request for your changes? When they’re merged in I’ll close this issue. Let me know if you need any further explanation.

**Comment by Chronowork1** [comment]
I think I just pushed my changes to the staging branch of Weave.

Do you want me to make another branch and push my changes to Weave?
