### ISSUE TITLE
Profile modifications for P2P

### ISSUE THREAD

**Issue by razzius** [razzius/weave#179]
Current profile:

![image](https://user-images.githubusercontent.com/2244895/77378965-b758d280-6d34-11ea-9214-bfdaf6b8141f.png)

- Change mentorship opportunities
- Which institutions have you done rotations for? (language TBD)

**Comment by razzius** [comment]
New profile draft is at https://github.com/razzius/weave/tree/razzi/p2p-form

**Comment by razzius** [comment]
![image](https://user-images.githubusercontent.com/2244895/85098098-32f4df00-b1bf-11ea-89a0-736067231d2a.png)

**Comment by jjchen20** [comment]
Let's add the free text "additional" section after "Parts of Me." We can
use the same wording for that section as the faculty profile.

Change "Student interest group support or speaking at student events" to
"Student interest group support."

I don't know how much med students will really be able to help with
networking. We could consider changing this to "Advice about classes or
clinical rotations."

**Comment by razzius** [comment]
"Additional" is down there, I just didn't capture it in that screenshot.

I'll update the checkboxes.

**Comment by razzius** [comment]
Opportunities differences:

Faculty:

    willing_shadowing
    willing_networking
    willing_goal_setting
    willing_discuss_personal
    willing_career_guidance
    willing_student_group

Student:

    willing_advice_classes
    willing_advice_clinical_rotations
    willing_discuss_personal
    willing_student_group
    willing_research
    willing_residency
    willing_student_group (will display as "Student interest group support")

Personally I feel like "willing to discuss student life" could be lumped in with "willing to discuss personal as well as professional"

**Comment by jjchen20** [comment]
I'm envisioning "student life" being more things like living in the dorms,
adjusting to the workload, being a student. Whereas "willing to
discuss personal as well as professional" are more identity related topics,
i.e. being first generation in medicine, encountering racism. We could be
more explicit that it's "willing to discuss personal and professional
identities and interests."

**Comment by razzius** [comment]
I'm open to that; do you think there are students out there who specifically would not be open to discussing student life? It's not that much more work to add one more field but every bit of information we request makes the process take longer

**Comment by jjchen20** [comment]
It's possible. Each field makes the process longer to build the profile or
for students to create a profile? I don't think it would take that much
time for students to click another button. We can delete student life to
keep it at 6 opportunities.

I'm noticing this field shows up twice in your above comment:
willing_student_group

**Comment by razzius** [comment]
Yup, fixed the duplicate.

It's not that much more data, to be fair, but another reason to consider going for 6 is that another checkbox would make the profile results taller or have to reduce padding to fit in the same amount of space:

![image](https://user-images.githubusercontent.com/2244895/85914578-c738f480-b804-11ea-8b46-985150823b46.png)

I'll leave it out for now and we can consider adding later; it's generally easier to add stuff than to take it away after all.

**Comment by razzius** [comment]
Still todo:
API
- [ ] endpoint to create student profile
- [ ] endpoint to edit student profile
- [ ] update profile starring endpoints to work with faculty and student profiles
- [ ] endpoint to query student profiles

UI
- [ ] separate student profile form from faculty profile form, hook up to navigation

**Comment by jjchen20** [comment]
For the student profile, change the description above "Parts of Me" so it
mentions students only and not faculty.
