### ISSUE TITLE
Update help page for peer-to-peer

### ISSUE THREAD

**Issue by razzius** [razzius/weave#216]
Currently all the profile editing stuff is called out as "faculty". We should read through and make sure it all makes sense in a peer-to-peer world.

**Comment by jjchen20** [comment]
Agreed, will need to disambiguate the language.

**Comment by razzius** [comment]
The help video could also be updated

**Comment by razzius** [comment]
Dependent on #179

**Comment by razzius** [comment]
So that the video has the proper form fields
